on:
  push:
  workflow_dispatch:

permissions:
  contents: write
jobs:
  set-version-tag:
    uses: './.github/workflows/settag.yml'
    secrets:
      inherit

  call-create-repo:
    needs: set-version-tag
    uses: 'tgiesela/repository.ziggotv/.github/workflows/createrepo.yml@master'
    secrets:
      inherit

  call-addzipfiles-workflow:
    needs: call-create-repo
    uses: 'ziggotv/ziggotv.github.io/.github/workflows/submit_zipfiles.yml@main'
    with:
      repo-zipfile: 'repo-zipfiles'
    secrets:
      inherit
